version: "3"
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
#    ports:
#      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: seshat
      POSTGRESQL_PASSWORD: seshat
      POSTGRESQL_DATABASE: seshat-prod
    volumes:
      - seshat_dbdata:/var/lib/postgresql/data

  seshat:
    build: .
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/seshat-prod'

volumes:
  seshat_dbdata:

