version: "3"
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: seshat
      POSTGRESQL_PASSWORD: seshat
      POSTGRESQL_DATABASE: seshat-dev
    volumes:
      - seshat_dbdata:/var/lib/postgresql/data

volumes:
  seshat_dbdata:

