version: "3"
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    network_mode: host
    environment:
      POSTGRESQL_USERNAME: seshat
      POSTGRESQL_PASSWORD: seshat
      POSTGRESQL_DATABASE: seshat-prod
    volumes:
      - seshat_dbdata:/var/lib/postgresql/data

  seshat:
    build:
      context: .
      args:
        POSTGRES_URL: ${POSTGRES_URL}
    network_mode: host
    environment:
      POSTGRES_URL: ${POSTGRES_URL}

volumes:
  seshat_dbdata:

